# app/api/endpoints.py
from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field
from typing import Dict, Any, List, Optional
from app.core.pipeline import pipeline

router = APIRouter(prefix="/chat", tags=["Chat Engine"])

# SESSION HISTORY (in-memory, last turn only)
# Keeps just the single most recent {"question", "sql"} turn per session so
# follow-ups ("their emails too", "narrow that down") can be resolved by the
# pipeline. Deliberately not a full conversation log — see pipeline.ask() docstring
# for why context is scoped to one turn back rather than open-ended memory.
#
# In-memory is fine for a single-process demo. For multiple workers or restarts,
# swap this dict for Redis (or similar) — the shape of what's stored doesn't change.
SESSION_HISTORY: Dict[str, Dict[str, str]] = {}


# PYDANTIC SCHEMAS FOR DATA VALIDATION
class QueryRequest(BaseModel):
    question: str = Field(
        ...,
        description="The natural language question to run against AdventureWorks.",
        example="Which employees are older than 40 years?"
    )
    session_id: Optional[str] = Field(
        "default",
        description="Identifies the conversation session, so follow-up questions "
                    "(e.g. 'show their emails too') can resolve context from the "
                    "previous turn. Defaults to a single shared session if omitted."
    )

class PerformanceMetrics(BaseModel):
    execution_time_seconds: float = Field(..., description="System execution duration in seconds.")

class QueryResponse(BaseModel):
    status: str = Field(..., description="Response status (success or error).")
    answer: Optional[str] = Field(None, description="Conversational answer generated by Gemini.")
    generated_sql: Optional[str] = Field(None, description="The raw Microsoft T-SQL translated and executed.")
    mode: Optional[str] = Field(
        None, description="'text' for small result sets rendered as prose, "
                           "'table' for large result sets meant for grid/table display."
    )
    row_count: Optional[int] = Field(None, description="Total number of rows returned by the query.")
    data: Optional[List[Dict[str, Any]]] = Field(
        None, description="Full structured result set (list of column-labeled records), "
                           "for the frontend to render directly — especially useful when mode='table'."
    )
    metrics: PerformanceMetrics
    error_message: Optional[str] = Field(None, description="Error details, if any occurred.")


# ENDPOINT DEFINITIONS
@router.post(
    "/query",
    response_model=QueryResponse,
    status_code=status.HTTP_200_OK,
    description="Processes a natural language question, translates it to T-SQL, and returns the response. "
                "Supports contextual follow-ups within a session (see session_id)."
)
async def process_natural_language_query(payload: QueryRequest):
    if not payload.question.strip():
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Question string cannot be empty."
        )

    session_id = payload.session_id or "default"
    last_turn = SESSION_HISTORY.get(session_id)
    history = [last_turn] if last_turn else []

    # Delegate the work entirely to our Core Pipeline singleton
    result = pipeline.ask(payload.question, history=history)

    if result["status"] == "error":
        # We return a structured validation schema rather than raising a hard 500 error,
        # so that your frontend UI can elegantly display the SQL error or translation failure.
        return QueryResponse(
            status="error",
            error_message=result.get("error_message"),
            metrics=PerformanceMetrics(
                execution_time_seconds=result["metrics"]["execution_time_seconds"]
            )
        )

    # Remember this turn so the *next* call from this session can reference it.
    if "turn" in result:
        SESSION_HISTORY[session_id] = result["turn"]

    return QueryResponse(
        status="success",
        answer=result.get("answer"),
        generated_sql=result.get("generated_sql"),
        mode=result.get("mode"),
        row_count=result.get("row_count"),
        data=result.get("data"),
        metrics=PerformanceMetrics(
            execution_time_seconds=result["metrics"]["execution_time_seconds"]
        )
    )


@router.post(
    "/reset",
    description="Clears the stored conversation context for a session, so the next "
                 "question starts fresh with no follow-up references resolved."
)
async def reset_session(session_id: str = "default"):
    SESSION_HISTORY.pop(session_id, None)
    return {"status": "success", "message": f"Session '{session_id}' context cleared."}